{% set name = "django-pwa" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 489532e2b742c69b19de529c7c422d7a98911645932ea05ea7e4fd43b4757b0d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pypandoc
    - python >=3.5
  run:
    - django >=1.8
    - python >=3.5

test:
  imports:
    - pwa
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/silviolleite/django-pwa
  summary: A Django app to include a manifest.json and Service Worker instance to enable progressive web app behavior
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - kcemenike
